#pragma once

#include <string>
#include <rapidjson/document.h>

namespace snuffbox
{
  namespace sparse
  {
    /**
    * @brief The class that handles all parsing functionality from a .json
    *        generated by header-parser
    *
    * @author Daniel Konings
    */
    class Parser
    {

    public:

      /**
      * @brief Parse the contents of a .json and output the parse result
      *        to a specific directory
      *
      * The parser automatically logs errors to std::cout, so that they can be
      * viewed during compilation.
      *
      * @param[in] input The path to the .json from the current 
      *                  working directory
      * @param[in] output The path to the file to output in the binary directory
      *
      * @return Was the parsing a success?
      */
      static bool Parse(const std::string& input, const std::string& output);

    protected:

      /**
      * @brief Parses the .json document after it has been parsed by
      *        rapidjson
      *
      * @param[in] doc The rapidjson document to parse
      *
      * @return Was the parsing a success?
      */
      static bool ParseDocument(const rapidjson::Document& doc);
    };
  }
}